version: "3"

services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    volumes:
      - gitea_data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "3022:22"

volumes:
  gitea_data: {}
